### ISSUE TITLE
several problems in hotstuff run

### ISSUE THREAD

**Issue by SenjiMuramasa** [relab/hotstuff#33]
Hi, I recently started to learn about Hotstuff related content, and I tried to run your code.  But I ran into a few problems running the code. I will show them in the pictures. I didn't make any changes when I ran the code, I just did the following steps:
1 make
2 ./hotstuff run
But the logs seem to indicate something unusual. Do these logs represent any problems in my operation? Or are these logs normal?
Thank you very much.
![图片1](https://user-images.githubusercontent.com/96971310/153864516-cb79cee0-0902-4357-be8c-07af39a2538d.png)
![图片2](https://user-images.githubusercontent.com/96971310/153864529-7e6d0f28-0625-4ae0-8fea-7901e53c9475.png)
![图片3](https://user-images.githubusercontent.com/96971310/153864535-e126c682-159d-40bb-93bc-077f4e2bf1e2.png)
![图片4](https://user-images.githubusercontent.com/96971310/153864544-e0ecd5ff-8632-4833-a2d2-68445b95d609.png)

**Comment by Raytar** [comment]
Hi!

None of these log messages indicate any serious issues. It's likely that they were all caused by messages arriving in a different order than expected. That can happen often, especially in a low-latency network.

I'll take a closer look at the sources of these log messages and consider if they should be reclassified as "debug" messages.

**Comment by SenjiMuramasa** [comment]
Thank you for your answer!
I am trying to do some experiments with your code, so I am wondering if you tested the performance of the code?
In addition, I see some content about fork in byzantine.go. Can fork be used directly? And how to use it?
I am new to hotstuff and Go, so my question may be low-level. I am very sorry to bother you.
Thank you very much.

**Comment by Raytar** [comment]
> I am trying to do some experiments with your code, so I am wondering if you tested the performance of the code?

We did some comparisons with `libhotstuff` a long time ago, but I haven't looked at the performance in a while.

> In addition, I see some content about fork in byzantine.go. Can fork be used directly? And how to use it?

Uhh, I just noticed that it doesn't work on `master`. 😅I've pushed a commit to fix it!
You can enable it using the `byzantine` flag:

```text
./hotstuff run --byzantine="fork:1"
```

The example above enables the "fork" behavior for a single replica. You could combine several byzantine behaviors also:

```text
./hotstuff run --byzantine="fork:1,silence:2"
```

This would enable the "fork" behavior for one replica, and the "silence" behavior for two replicas.

**Comment by SenjiMuramasa** [comment]
Thank you very much!

I have tried using a fork attack but the code is stuck.
![fork](https://user-images.githubusercontent.com/96971310/155825727-0779bcb3-c81e-4d8c-b610-b4580543f81a.png)
So I wonder if this is a sign of a success attack? Should this trigger the timeout system to go to the next view?

And, I want to try using Batch to improve the system throughput. I changed batch-size in the run.go file, but the result was 0.
![batch1](https://user-images.githubusercontent.com/96971310/155826089-191563e0-8f7b-4b60-8d9e-bd5993a26570.png)
![batch2](https://user-images.githubusercontent.com/96971310/155826092-5ce15cfd-644a-444b-a9e0-832a999bd8c6.png)
Are there any other configuration changes that need to be made?

Again, thank you for your patient reply.

**Comment by Raytar** [comment]
It looks like the default setting for `max-concurrent`, which controls the number of concurrent commands a client can issue, is too low for a fork scenario. This setting must be changed if you change the batch size. It should be at least 4 times the batch size if you are using a single client.

Going back to the fork attack, by increasing `max-concurrent` from 4 (the default) to 10, I get this result:

```text
executed: 4900, failed: 1634
```

The failed commands shows that the fork attack was successful.

Now, you can compare with the `fasthotstuff` implementation:

```
./hotstuff run --consensus="fasthotstuff" --byzantine="fork:1" --max-concurrent=10 --timeout-multiplier=1
```

(setting `--timeout-multiplier` to 1 here stops the view-synchronizer from increasing the view duration when a timeout occurs)

This gives me the result: `executed: 1510, failed: 0`, showing that the `fasthotstuff` implementation is indeed resistant to forking attacks :)

**Comment by SenjiMuramasa** [comment]
Thank you! It helps a lot. 
After increasing 'max-concurrent' from 4 to 10, the code started to run. But it seems the code can only run for a short time. I tried to continue increasing the 'max-concurrent' and it worked a little better. But it still doesn't run to the end. (I increased 'duration' to 60 seconds)
![fork](https://user-images.githubusercontent.com/96971310/155923078-f9b9edd7-abb9-4d8f-a099-3e54a67d42b1.png)
I'm using a virtual machine to run the code on Linux21. Is that the cause of the problem?

**Comment by SenjiMuramasa** [comment]
Hi, I tried to run the code many times, sometimes the code would run longer, and sometimes it would just get stuck.
According to the number of final executions and failures, the attack was successful.

These two images represent two typical cases (duration=10s, max-concurrent=10).
The first one stuck as soon as it started running.
![2](https://user-images.githubusercontent.com/96971310/156874229-4f4e1aa3-98e1-4507-9f26-7966e48d94c7.png)

The second one ran almost to the end of the duration.
![1](https://user-images.githubusercontent.com/96971310/156874275-2d716add-3540-4d52-ba7d-1eeabd01eb36.png)

Do you have this kind of problem? Or was it just me, for some other reason?

**Comment by Raytar** [comment]
Sorry for the slow response. It looks to me like this is the client getting stuck due to some unacknowledged commands (or maybe unordered?). I am not quite sure why it happens. To remedy this, I have added a timeout to the client that is configurable through the `--client-timeout` flag (defaults to 500ms).

**Comment by SenjiMuramasa** [comment]
Hello, here I go again~~
I tried overwriting two blocks with a fork attack, but it seems the malicious block didn't get into the chain. Where can I modify so that the malicious blocks can be saved in the chain?
Thank you!

**Comment by Raytar** [comment]
It's hard for me to tell exactly why the malicious block is not accepted without any more detail, but here is how it normally works:

1. One of the replicas creates the new block and proposes it to the other replicas. This is usually done by the `Consensus.Propose` method. However, the `ProposeRuler` interface allows the behavior of this to be changed, which is how the byzantine package works.
2. All replicas then process the block in the `OnPropose` function. This function verifies the block's quorum certificate, checks the identity of the proposer, and then checks the `VoteRule` of the consensus protocol. If all these checks pass, the command(s) stored in the block are inspected by the `Acceptor` module. If the `Acceptor` module accepts the command(s), then the block is accepted. Currently, the `Acceptor` module checks the serial numbers of commands to ensure that only new commands are accepted. This is implemented in the file `replica/cmdcache.go`
3. Depending on the consensus protocol, the block will be committed into the chain when its grandchild or great-grandchild is proposed (assuming that all blocks in between are accepted too).

PS: I'm converting this issue into a discussion, as I think that is more appropriate ;)
